### ISSUE TITLE
ClassCastException when passing a map of options to `read-value` or `write-value`

### ISSUE THREAD

**Issue by lambdahands** [metosin/jsonista#13]
Hi there,

I was trying out `jsonista`, and I noticed the docstrings for `read-value` and `write-value` state:

> To configure, pass in an ObjectMapper created with [[object-mapper]], or pass in a map with options.

I'm able to pass in an `ObjectMapper` with no issues:

```clj
(require '[jsonista.core :as j])
(j/read-value "{\"hello\": 1}" (j/object-mapper {:decode-key-fn true}))
;; => {:hello 1}

(require '[clojure.string :as str])
(j/write-value-as-string {:hello 1} (j/object-mapper {:encode-key-fn (comp str/upper-case name)}))
;; => "{\"HELLO\":1}"
```

However, if I only pass a map I get an error:

```clj
(j/read-value "{\"hello\": 1}" {:decode-key-fn true})
;; ClassCastException clojure.lang.PersistentArrayMap cannot be cast to com.fasterxml.jackson.databind.ObjectMapper  jsonista.core/eval221/fn--222 (core.clj:142)

(j/write-value-as-string {:hello 1} {:encode-key-fn (comp str/upper-case name)})
;; ClassCastException clojure.lang.PersistentArrayMap cannot be cast to com.fasterxml.jackson.databind.ObjectMapper  jsonista.core/write-value-as-string (core.clj:203)
```

**Comment by ikitommi** [comment]
Good catch! The docs were out of sync and [fixed](https://github.com/metosin/jsonista/commit/b2a3074f7f403730f7d781b3554361b8ca8911a7) now.

We removed the automatic option map coercion into `object-mapper` both to make the functions bit faster and to make the cost of configuration visible. Creation of `object-mapper` has a cost and it should be created once and reused in encoding & decoding.

**Comment by lambdahands** [comment]
Awesome, thanks for the quick response! 😄
