### ISSUE TITLE
CNF Exception for jackson 2.10.0

### ISSUE THREAD

**Issue by RokLenarcic** [metosin/jsonista#24]
If you upgrade `[com.fasterxml.jackson.core/jackson-databind "2.9.9"]` to `2.10.0` you will get this message when compiling project:

```
Syntax error compiling new at (jsonista/core.clj:79:38).
Syntax error (ClassNotFoundException) compiling new at (jsonista/core.clj:79:38).
com.fasterxml.jackson.core.exc.InputCoercionException
```

The reason I bumped the version was 6 CVEs for version `2.9.9`.

**Comment by miikka** [comment]
@RokLenarcic, did you also upgrade `jackson-core` to `2.10.0`?

**Comment by RokLenarcic** [comment]
Not explicitly, no. I assumed that a version of databind also pulls the same version of core as dependency, but it looks like someone specifically requires core at `2.9.6`. Specifying core version fixes this. Thanks.
