### ISSUE TITLE
Decoder options

### ISSUE THREAD

**Issue by miikka** [metosin/jsonista#5]
From https://github.com/metosin/muuntaja/issues/23:

> Cheshire has `:key-fn`, `:array-coerce-fn` and `:bigdecimals?`,  Ring-json has  `:keywords?` (setting the `:key-fn` actually), Muuntaja has now `:keywordize?`.
> 
> Would be good to check the `muuntaja.json` and `muuntaja.format.json/make-muuntaja-json-encoder` options before release.

**Comment by ikitommi** [comment]
Today, I think the `:key-fn` would be better than `:keywords?`: one common case is to snake/kebab-case keys - could be enabled in a single sweep instead of post-walking the structure.

**Comment by ikitommi** [comment]
`:key-fn` is supported now as `:encode-key-fn` and `:decode-key-fn`.

**Comment by ikitommi** [comment]
I think this is ok
