### ISSUE TITLE
perf charts are confusing

### ISSUE THREAD

**Issue by puredanger** [metosin/jsonista#54]
Hi, I'm confused by the Clojure JSON decoding chart at https://github.com/metosin/jsonista/blob/master/README.md#performance - I would expect the relative chart to have highest number at 100% for each column set, as in the Clojure JSON encoding chart but it maxes at like 60%. Bad divisor in the spreadsheet under the graph maybe?

Also, data.json version is lagging - newest is 2.3.1.

**Comment by ikitommi** [comment]
the percents are compared to fastest tested library, which is Jsonista for encoding and Jackson for decoding. Will fix so that it doesn't compare to solutions not plotted on that chart.

**Comment by ikitommi** [comment]
re-run tests, fixed charts.

**Comment by puredanger** [comment]
Ah, that makes sense. Thanks!
