### ISSUE TITLE
`write-value` closes the object

### ISSUE THREAD

**Issue by helins** [metosin/jsonista#61]
Writing to an object in a streaming fashion is a typical use case and since Jsonista aims for performance, supporting that is rather expected. As opposed to using `write-value-as-string` or `write-value-as-bytes` and then copying the result to an object like a writer.

Currently, this is not possible since `write-value` closes the given object, hence an exception is thrown. Or maybe is it Jackson itself?

I realized this while trying to write a line-delimited JSON file.

```clojure
(with-open [out (clojure.java.io/writer "/tmp/foo.json")]
    (json/write-value out [:a])
    (.write out (int \newline))
    (json/write-value out [:b]))
```

**Comment by FiV0** [comment]
Workaround for now (credit @jarohen)
```clj
(do
  (let [obj-mapper (doto (jsonista.core/object-mapper)
                     (.disable (into-array com.fasterxml.jackson.core.JsonGenerator$Feature [com.fasterxml.jackson.core.JsonGenerator$Feature/AUTO_CLOSE_TARGET])))]
    (with-open [out (io/output-stream "/tmp/foo.json")
                wrt (io/writer out)]
      (jsonista.core/write-value wrt {"foo" 1} obj-mapper)
      (.write wrt "\n")
      (jsonista.core/write-value wrt {"bar" 1} obj-mapper)))
  (slurp "/tmp/foo.json"))
```

**Comment by jarohen** [comment]
Could add it into the `cond->` when you build up the mapper in `j/object-mapper`?

`(:close-targets? options) (doto (-> .getFactory (.disable JsonGenerator$Feature/AUTO_CLOSE_TARGET)))`

(Happy to raise a PR or have you guys add it in, whatever's easier for you :slightly_smiling_face:)
