### ISSUE TITLE
Deserizlize Joda Datetime

### ISSUE THREAD

**Issue by tomer8888** [metosin/jsonista#76]
Following the README example, how can I deserialize back to clj-time?

```
;; [com.fasterxml.jackson.datatype/jackson-datatype-joda "2.9.5"]
(import '[com.fasterxml.jackson.datatype.joda JodaModule])
(import '[org.joda.time LocalDate])

(def mapper
  (j/object-mapper
    {:modules [(JodaModule.)]}))

(j/write-value-as-string (LocalDate. 0) mapper)
; "\"1970-01-01\""

(j/read-value *1 mapper) 
; => "1970-01-01"

**Comment by ikitommi** [comment]
Hi. The parser doesn't know that a string should be parsed into some object. You should companion jsonista with something like [malli](https://github.com/metosin/malli) to define a schema for the data and apply a type-transformation on top of the normal JSON parsing.

```js
let date = new Date();
// Tue Jul 09 2024 16:52:37 GMT+0300 (Eastern European Summer Time)

JSON.stringify(date)
// '"2024-07-09T13:52:37.434Z"'

JSON.parse(JSON.stringify(date))
// '2024-07-09T13:52:37.434Z'
```

**Comment by ikitommi** [comment]
with malli, using plain `Date`s (transformers supported out-of-the-box):

```clojure
(j/write-value-as-string {:date (java.util.Date.)})
; => "{\"date\":\"2024-07-09T13:59:00Z\"}"

(j/read-value *1 j/keyword-keys-object-mapper)
; => {:date "2024-07-09T13:59:00Z"}

(m/decode [:map [:date inst?]] *1 mt/json-transformer)
; => {:date #inst"2024-07-09T13:59:00.000-00:00"}
```

**Comment by tomer8888** [comment]
@ikitommi thanks but i'm looking for a more robust solution based on the object mapper (tagged json maybe?)

**Comment by ikitommi** [comment]
By robust, you mean self-contained? Parsing strings that look like dates always into dates is not robust, convenient maybe. You can look for Tagged JSON if you don't want to go the malli way. Hope you'll find a good enough solution for this.
